/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#f7f9fe",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eff1f6",
        "inverse-primary": "#b7c4ff",
        "inverse-surface": "#2d3135",
        "on-background": "#181c20",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-primary-container": "#8593cd",
        "on-primary-fixed": "#05164b",
        "on-primary-fixed-variant": "#354479",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#007150",
        "on-secondary-fixed": "#002115",
        "on-secondary-fixed-variant": "#005139",
        "on-surface": "#181c20",
        "on-surface-variant": "#45464f",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#d08500",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        "outline": "#767680",
        "outline-variant": "#c6c5d1",
        "primary": "#021449",
        "primary-container": "#1b2a5e",
        "primary-fixed": "#dce1ff",
        "primary-fixed-dim": "#b7c4ff",
        "secondary": "#006c4d",
        "secondary-container": "#70f8c2",
        "secondary-fixed": "#73fac4",
        "secondary-fixed-dim": "#53dda9",
        "surface": "#f7f9fe",
        "surface-bright": "#f7f9fe",
        "surface-container": "#eceef3",
        "surface-container-high": "#e6e8ed",
        "surface-container-highest": "#e0e2e7",
        "surface-container-low": "#f1f4f9",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d8dadf",
        "surface-tint": "#4e5c92",
        "surface-variant": "#e0e2e7",
        "tertiary": "#271500",
        "tertiary-container": "#432800",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "display":  ["Bricolage Grotesque", "sans-serif"],
        "ui":       ["Inter", "sans-serif"],
        "mono":     ["JetBrains Mono", "monospace"],
        "sans":     ["Inter", "sans-serif"],
        // Legacy aliases
        "headline": ["Bricolage Grotesque", "sans-serif"],
        "body":     ["Inter", "sans-serif"],
        "label":    ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [],
}